### ISSUE TITLE
Crash with mobs extending EntityPlayer using XPBoost enchanted weapons

### ISSUE THREAD

**Issue by olee** [tterrag1098/ttCore#35]
There is that mod LittleMaidMobX which adds followers that extend EntityPlayer.
If you give them a weapon with XPBoost entchantment and let them kill a mob, the game will crash with the following ClassCastException. Should be easy to fix by adding an instanceof check.

```
java.lang.ClassCastException: littleMaidMobX.entity.EntityLittleMaid cannot be cast to net.minecraft.entity.player.EntityPlayer
        at tterrag.core.common.handlers.XPBoostHandler.handleEntityKill(XPBoostHandler.java:53) ~[XPBoostHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_650_XPBoostHandler_handleEntityKill_LivingDeathEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303) [ForgeHooks.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:891) [sv.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855) [sv.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:54) [yg.class:?]
        at net.minecraft.entity.monster.EntityZombie.func_70097_a(EntityZombie.java:222) [yq.class:?]
        at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(SourceFile:270) [zc.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2070) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) [mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2034) [ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1887) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by tterrag1098** [comment]
Fixed in above commit

**Comment by olee** [comment]
Thanks for the fix - don't you want to close this issue then? :smiley:
